### ISSUE TITLE
Failed to upload snapshot in minio s3 

### ISSUE THREAD

**Issue by sharmavijay86** [vmware-tanzu/velero-plugin-for-vsphere#156]
Hi Team,
i am currently testing this feature for **block provisioner   csi.vsphere.vmware.com**  in my airgapped tkg environment on vsphere 6.7u3.

The problem here is , when i am taking backup as bellow   
```
 velero backup create my-backup --include-namespaces=nginx-example --snapshot-volumes --volume-snapshot-locations vsphere
```
Backup completed partially success.

```
~$ velero backup describe my-backup
Name:         my-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  PartiallyFailed (run `velero backup logs my-backup` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  nginx-example
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-08-11 13:07:34 +0000 UTC
Completed:  2020-08-11 13:07:43 +0000 UTC

Expiration:  2020-09-10 13:07:34 +0000 UTC

Total items to be backed up:  27
Items backed up:              27

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
```

Now when i am runing to check snapshot upload  it gives upload failed.

```
~$ kubectl get -n velero uploads.veleroplugin.io -o yaml
```
Bello is error

```
  status:
    currentBackOff: 32
    message: 'Failed to upload snapshot, ivd:11959489-aecd-48e0-8634-4728b7dc59a9:be658bf6-ed86-438d-abc9-829917bde84a,
      to durable object storage. Prepare for access failed. The error code is 3014.
      with error code: 3014'
    nextRetryTimestamp: "2020-08-11T13:50:46Z"
    phase: UploadError
    processingNode: gks-rat-stg-3-md-0-7659ffb99f-74m9g
    progress: {}
    retryCount: 6
    startTimestamp: "2020-08-11T13:07:43Z"
```
If you can help in what causing this error.
