### ISSUE TITLE
Thin-provisioned VMDKs inflated during upload process

### ISSUE THREAD

**Issue by dacodas** [vmware-tanzu/velero-plugin-for-vsphere#296]
# Overview

It appears that thin-provisioned VMDKs on the datastore are being inflated during upload process to S3-compatible storage.

Is there any roadmap to being able to upload the thin VMDKs or otherwise save space?

You can see in the logs and the minio snapshot below that 3G has been uploaded whereas in the vSphere snapshot, the different disk components don't sum up to nearly that much.

![minio-gateway](https://user-images.githubusercontent.com/8251516/106795760-5914a580-660f-11eb-8747-21ea48194b3d.png)

![datastore-vmdks](https://user-images.githubusercontent.com/8251516/106795768-5ca82c80-660f-11eb-91e9-a4bf3e998194.png)

# Additional information

## `velero` deployment images

```
image: velero/velero:v1.5.2
image: velero/velero-plugin-for-aws:v1.1.0
image: velero/velero-plugin-for-microsoft-azure:v1.1.0
image: vsphereveleroplugin/velero-plugin-for-vsphere:1.1.0
image: velero/velero-plugin-for-csi:v0.1.2
```

## Persistent volume

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    example-vsphere-csi-backup: "yes"
  name: example-vsphere-csi-v2-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: vsphere-csi-v2
```

## Backup

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: minio-gateway
  name: example-vsphere-csi-v2-backup-2021-02-02t15-48-08-00
  namespace: backup
spec:
  defaultVolumesToRestic: true
  includedNamespaces:
  - default
  labelSelector:
    matchExpressions:
    - key: example-vsphere-csi-backup
      operator: Exists
  storageLocation: minio-gateway
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - vsl-vsphere
```

## `minio` pod and service

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: minio-gateway
  name: minio-gateway
  namespace: backup
spec:
  containers:
  - args:
    - gateway
    - azure
    envFrom:
    - secretRef:
        name: minio-azure-credentials
    image: minio/minio
    imagePullPolicy: Always
    name: minio-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: minio-gateway
  namespace: backup
spec:
  selector:
    run: minio-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
```

## BackupStorageLocation

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: minio-gateway
  namespace: backup
spec:
  backupSyncPeriod: 2m0s
  provider: aws
  objectStorage:
    bucket: velero
    prefix: example-prefix
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio-gateway.backup.svc

    # AWS profile within the credentials file to use for the backup storage location.
    # This is mounted within the velero pod
    profile: default
```
