### ISSUE TITLE
Consider the ability to explicitly configure image names

### ISSUE THREAD

**Issue by aceeric** [vmware-tanzu/velero-plugin-for-vsphere#379]
This relates to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/378

We're installing velero, and the velero plugin for aws, and velero plugin for vsphere in an air-gapped environment using the helm chart https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.23.3

In our air-gapped registry we import images from many external registries and organizations. To minimize the possibility of name collisions we mangle image names. So `docker.io/velero/velero-plugin-for-vpshere` becomes `our-internal-registry/our-project/velero-velero-plugin-for-vpshere`

It would be useful for us (and potentially others) to be able to explicitly override the images spawned by the plugin directly in the helm chart. E.g.:
```
values:
  initContiainers:
  - name: velero-plugin-for-vsphere
    image: our-internal-registry/our-project/velero-velero-plugin-for-vpshere
    args:
    - backup-driver-repo=velero-backup-driver
    - data-manager-for-plugin-repo=velero-data-manager-for-plugin
```
Or something akin to that. Basically, to be able to explicitly override the constant value in the go code... It's hard to anticipate everyone's configuration so the ability to explicitly define images is often useful.
