### ISSUE TITLE
Unable to backup vSphere persistent volumes to S3 (Access Denied)

### ISSUE THREAD

**Issue by tomasodehnal** [vmware-tanzu/velero-plugin-for-vsphere#404]
**Describe the bug**

I'm unable to backup persistent volumes hosted on vSphere to AWS S3. While backing up other resources works, the persistent volumes are snapshot but the upload fails with error:
```
Failed to upload snapshot, ivd:b4cc071c-604a-4d1b-98dd-5eabbbc3a1fb:9bcceeb4-d4b9-42fd-a2e5-5b00b6c30576, to durable object storage. AccessDenied: Access Denied
status code: 403, request id: ETATBT9JD93Q1HB9, host id: <redacted>
```
Similar message is present in the Velero backup log:
```
An error occurred: request failed: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>71TP4DADY1ZQ8NE2</RequestId><HostId><redacted></HostId></Error>
```

**To Reproduce**

0. Create AWS S3 bucket, set the permissions according to <https://github.com/vmware-tanzu/velero-plugin-for-aws#Set-permissions-for-Velero> and create the `aws-creds` file:
    ```
    [default]
    aws_access_key_id=<redacted>
    aws_secret_access_key=<redacted>
    ```

1. Install Velero:
   Create `values.yaml` file:
    ```
    configuration:
      provider: aws
      backupStorageLocation:
        name: aws
        bucket: <redacted>
        default: true
        config:
          region: eu-central-1
      volumeSnapshotLocation:
        name: aws
        config:
          region: eu-central-1
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.3.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    serviceAccount:
      server:
        create: true
        name: velero
    credentials:
      name: cloud-credentials
    ```
   Install the server with helm command:
    ```
    helm upgrade --install velero vmware-tanzu/velero \
    --namespace velero \
    --create-namespace \
    --set-file credentials.secretContents.cloud=./aws-creds \
    -f ./values.yaml
    ```
2. Install vSphere Plugin:
    ```
    velero plugin add vsphereveleroplugin/velero-plugin-for-vsphere:v1.2.1
    ```

3. Create example deployment by applying the nginx-example manifest from Velero cli archive (velero-v1.7.0-linux-amd64):
    ```
    kubectl apply -f examples/nginx-app/with-pv.yaml
    ```
4. Create the backup with:
    ```
    velero create backup nginx --include-namespaces nginx
    ```

**Expected behavior**

When the backup is created, not only the K8s manifests but also the persistent volumes are backed up to S3.

**Troubleshooting Information**

- vSphere 7.0.2 (both vCenter and ESXi server)
- Vanilla K8s 1.18.4
- vSphere CSI image versions:
  ```
    Image:         gcr.io/cloud-provider-vsphere/csi/ci/driver:latest
    Image:         gcr.io/cloud-provider-vsphere/csi/ci/syncer:latest
    Image:         k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
    Image:         k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
    Image:         k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
    Image:         k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
    Image:         k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
  ```

**Screenshots**

N/A

**Anything else you would like to add:**

N/A
