### ISSUE TITLE
Upload to & delete backup from Hitachi Vantara Storage (HCP) fails

### ISSUE THREAD

**Issue by sb-ev** [vmware-tanzu/velero-plugin-for-vsphere#417]
## Describe the bug

1. Upload to Hitachi Vantara Storage (HCP) 9.1.0.173 fails.
2. Delete Backup from Hitachi Vantara Storage (HCP) 9.1.0.173 fails.

## To Reproduce

Our setup is the following:

* vCenter 7U3a
* Supervisor:
  * Velero vSphere Service 1.1.0
  * Velero vSphere Operator 1.1.0
  * Velero 1.5.1
  * AWS_PLUGIN v1.2.1
  * VSPHERE_PLUGIN v1.2.1
  * BACKUP_DRIVER v1.2.1
  * DATA_MANAGER v1.2.0
* TKC Cluster:
  * AWS_PLUGIN v1.2.1
  * VSPHERE_PLUGIN v1.2.1
  * BACKUP_DRIVER v1.2.1
* Velero Client: 1.6.0
* Storage: Hitachi Vantara Storage (HCP) 9.1.0.173

We create a backup via `velero backup create -l app=cassandra`.  
The backup is in `Completed` state.  
We can see the snapshots both on the TKC and the supervisor. 

### Ad 1: The upload fails with the following messages

```log
time="2021-11-18T11:42:05Z" level=info msg="Using explicitly found credentials for S3 repository access." logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/utils/utils.go:424"
time="2021-11-18T11:42:05Z" level=info msg="No such key caCert in params map" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/utils/utils.go:464"
time="2021-11-18T11:42:05Z" level=info msg="Got true for s3ForcePathStyle, setting s3ForcePathStyle to true" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/utils/utils.go:386"
time="2021-11-18T11:42:05Z" level=info msg="Created S3 repo type=ivd bucket=tkg-backups prefix=plugins/vsphere-astrolabe-repo/" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/s3repository/repository_protected_entity_type_manager.go:70"
time="2021-11-18T11:42:05Z" level=info msg="Copying the snapshot from local to remote repository" Local PEID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:103"
time="2021-11-18T11:42:05Z" level=info msg="Checking vCenter connections..." logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:301"
time="2021-11-18T11:42:05Z" level=info msg="vCenter connected, proceeding with operation" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:309"
time="2021-11-18T11:42:05Z" level=info msg="Registering a in-progress cancel function." Local PEID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:111"
time="2021-11-18T11:42:05Z" level=info msg="Registered a on-going cancel function." PEID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:227"
time="2021-11-18T11:42:05Z" level=info msg="GetInfo called on IVD Protected Entity, ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity.go:269"
time="2021-11-18T11:42:05Z" level=info msg="Checking vCenter connections..." logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:301"
time="2021-11-18T11:42:05Z" level=info msg="vCenter connected, proceeding with operation" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:309"
time="2021-11-18T11:42:05Z" level=info msg="GetDataReader called on IVD Protected Entity, ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity.go:59"
time="2021-11-18T11:42:05Z" level=info msg="Checking vCenter connections..." logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:301"
time="2021-11-18T11:42:05Z" level=info msg="vCenter connected, proceeding with operation" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:309"
2021-11-18T11:42:05.812Z warning -[00025] [Originator@6876 sub=Default] Closing Response processing in unexpected state: 3
2021-11-18T11:42:05.816Z warning -[00008] [Originator@6876 sub=vimaccess] cannot get thumbprint: SSL error code '151441516', exception: 'Wrong X.509 Certificate format'
2021-11-18T11:42:05.987Z warning -[00025] [Originator@6876 sub=Default] Closing Response processing in unexpected state: 3
2021-11-18T11:42:05.988Z warning -[00008] [Originator@6876 sub=vimaccess] cannot get thumbprint: SSL error code '151441516', exception: 'Wrong X.509 Certificate format'
time="2021-11-18T11:42:06Z" level=info msg="GetMetadataReader called on IVD Protected Entity, ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity.go:180"
time="2021-11-18T11:42:06Z" level=info msg="Checking vCenter connections..." logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:301"
time="2021-11-18T11:42:06Z" level=info msg="vCenter connected, proceeding with operation" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/ivd/ivd_protected_entity_type_manager.go:309"
2021-11-18T11:42:06.608Z warning -[00022] [Originator@6876 sub=Default] Closing Response processing in unexpected state: 3
2021-11-18T11:42:06.614Z warning -[00021] [Originator@6876 sub=vimaccess] cannot get thumbprint: SSL error code '151441516', exception: 'Wrong X.509 Certificate format'
time="2021-11-18T11:42:06Z" level=error msg="Failed at copying to remote repository" Local PEID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5" error="Failed to delete peinfo from bucket \"tkg-backups\": Unable to delete object \"plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5\" from bucket \"tkg-backups\": NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: , host id: " error.file="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.4.0/pkg/s3repository/repository_protected_entity.go:183" error.function=github.com/vmware-tanzu/astrolabe/pkg/s3repository.ProtectedEntity.deleteSnapshotComponents logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:120"
time="2021-11-18T11:42:06Z" level=info msg="CopyToRepo Error Received: Failed to delete peinfo from bucket \"tkg-backups\": Unable to delete object \"plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5\" from bucket \"tkg-backups\": NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: , host id: " controller=upload generation=77 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:363" name=upload-3d5e888b-f825-4a6e-9e8a-3b04e7368ed5 namespace=tkg-shared-services phase=UploadError snapshotID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5"
time="2021-11-18T11:42:06Z" level=info msg="Upload status updated from InProgress to UploadError" controller=upload generation=78 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:497" name=upload-3d5e888b-f825-4a6e-9e8a-3b04e7368ed5 namespace=tkg-shared-services phase=InProgress snapshotID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5"
time="2021-11-18T11:42:06Z" level=error msg="Failed to upload snapshot, ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5, to durable object storage. Failed to delete peinfo from bucket \"tkg-backups\": Unable to delete object \"plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5\" from bucket \"tkg-backups\": NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: , host id: " controller=upload generation=77 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:379" name=upload-3d5e888b-f825-4a6e-9e8a-3b04e7368ed5 namespace=tkg-shared-services phase=UploadError snapshotID="ivd:01c598c7-0c53-4fda-8124-ca8c7ec9dcc6:3d5e888b-f825-4a6e-9e8a-3b04e7368ed5"
```

### Ad 2: `velero backup delete` is stuck in deleting phase

`velero backup describe cassandra-backup-1`:

```yaml
Name:         cassandra-backup-1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.20.9+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20
 
Phase:  Deleting
 
Errors:    0
Warnings:  0
 
Namespaces:
  Included:  *
  Excluded:  <none>
 
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
 
Label selector:  app=cassandra
 
Storage Location:  default
 
Velero-Native Snapshot PVs:  auto
 
TTL:  720h0m0s
 
Hooks:  <none>
 
Backup Format Version:  1.1.0
 
Started:    2021-11-17 13:12:49 +0000 UTC
Completed:  2021-11-17 13:12:58 +0000 UTC
 
Expiration:  2021-12-17 13:12:49 +0000 UTC
 
Total items to be backed up:  9
Items backed up:              9
 
Velero-Native Snapshots: <none included>
 
Deletion Attempts (1 failed):
  2021-11-18 12:27:59 +0000 UTC: Processed
  Errors:
    rpc error: code = Unknown desc = NoSuchKey: The specified key does not exist.
  status code: 404, request id: , host id:
```

Log from the `velero` pod:

```log
time="2021-11-18T13:53:48Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: , host id: " error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:361" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:182"
```

## Expected behavior

1. Upload of snapshots works
2. Deletion of backups works
